# Generated by Django 5.1.4 on 2026-03-27 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_permission_role_alter_roleuser_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleuser',
            name='role',
            field=models.ForeignKey(default='User', on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='main.role'),
        ),
    ]
