# Generated by Django 5.1.4 on 2026-03-27 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_roleuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleuser',
            name='role',
            field=models.ForeignKey(default='User', on_delete=django.db.models.deletion.CASCADE, to='main.role'),
        ),
    ]
