# Generated by Django 5.1.4 on 2026-03-28 07:18

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_roleuser_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='permission',
            managers=[
                ('everithing', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='role',
            managers=[
                ('everithing', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='permission',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
