# Generated by Django 5.1.4 on 2026-03-28 09:04

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_permission_managers_alter_role_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('everithing', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='order',
            managers=[
                ('everithing', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='orderdetails',
            managers=[
                ('everithing', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('everithing', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='rolepermission',
            managers=[
                ('everithing', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='roleuser',
            managers=[
                ('everithing', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roleuser',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
