# Generated by Django 5.1.4 on 2026-03-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_category_managers_alter_order_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Process', 'Process'), ('Completed', 'Completed')], default='pending', max_length=15),
        ),
    ]
