# Generated by Django 5.1.4 on 2026-03-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_orderdetails_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
