# Generated by Django 5.1.4 on 2026-04-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_register_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='otp',
            field=models.CharField(default='', max_length=10),
        ),
    ]
